# Generated by Django 2.2.3 on 2019-07-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tag', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('image', models.FileField(upload_to='images/')),
            ],
        ),
    ]
